### PR TITLE
Link to `remake` in the README

### PR DESCRIPTION
**Pull request by cooljeanius**
`remake` is an interactive Makefile debugger based on GNU make: [https://github.com/rocky/remake](https://github.com/rocky/remake)
Think like `gdb` or `bashdb`, except for Makefiles. Besides the debugger, it also adds additional tracing output, and a few other additional features.

### CODE REVIEW

**Comment by cooljeanius** [comment]
cc @mcandre

**Comment by yarikoptic** [comment]
image

**Comment by yarikoptic** [comment]
sorry -- came out quite "big" ;)

**Comment by cooljeanius** [comment]
> sorry -- came out quite "big" ;)

...wow, AI certainly seems to have trouble with ropes...

**Comment by yarikoptic** [comment]
I like more the cyclopes in the audience ;)  but it did manage to spell @rocky 's name correctly (on 2nd try though)

**Comment by mcandre** [comment]
Not a static analyzer.

Not a bad tool, though! Recommend publishing this on one of the Awesome Lists.

**Comment by cooljeanius** [comment]
> Not a static analyzer.

The section this PR would add it to isn't just static analyzers, though? Like, none of ninja, nmake, rake, or shake are static analyzers, either...

**Pull request closed without merging**
