### PR TITLE
add config for pre-commit

### PR DESCRIPTION
**Pull request by ccoVeille**
Related to #242

### CODE REVIEW

**Comment by ccoVeille** [comment]
@nikosavola

could you tell me if this work if you add it to your .pre-commit-config.yaml

```yaml
  - repo: https://github.com/ccoveille/unmake
    rev: 38b03e7cbe1c28bcb8d33c1b2dcff8f50bf743ad
    hooks:
      - id: unmake
```

**Comment by ccoVeille** [comment]
I will assume you are not interested and somehow rude.

Bye, great tool anyway.

**Comment by nikosavola** [comment]
> @nikosavola
> 
> could you tell me if this work if you add it to your .pre-commit-config.yaml
> 
> ```yaml
>   - repo: https://github.com/ccoveille/unmake
>     rev: 38b03e7cbe1c28bcb8d33c1b2dcff8f50bf743ad
>     hooks:
>       - id: unmake
> ```

This seems to work, thanks!

**Comment by ccoVeille** [comment]
OK so, the PR only have to be merged and it would work without any further work.

So if @mcandre would reconsider merging it, it would be all set.

**Comment by mcandre** [comment]
Does the pre-commit system really require inserting code into the source code of the tool it's trying to wrap?! More bad design.

No one has mentioned forking unmake. You can do this as well. I'm certainly not splashing any such nonsense in this repo.

**Comment by ccoVeille** [comment]
No, precommit doesn't require it.

It just way you could provide guidance for people to use unmake with precommit.

It's the same way, you are documenting things.

But anyway, I won't argue as it seems there is nothing I can do to convince you people using precommit who loves your tool would expect and appreciate having an official support and guidance for using your tool with precommit.

You make me feel you somehow hate tge fact precommit exists, and give a solution for a need.

I quit.

Respectfully

**Comment by ccoVeille** [comment]
For anyone interested, here is the repository I made to support unmake in pre-commit.

https://github.com/ccoVeille/pre-commit-unmake

I'm looking for testers
- https://github.com/ccoVeille/pre-commit-unmake/issues/1

**Pull request closed without merging**
